name: data_viz
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - notebook
  - numpy
  - pandas
  - plotly
  - seaborn
  - pip
  - pip:
      - country_converter==1.3.2
      - kaleido